# Generated by Django 3.1.7 on 2021-03-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Тестовая запись', max_length=200),
            preserve_default=False,
        ),
    ]
